[package]
name = "fack-core"
version = "0.4.0"
edition = "2024"
description = "Foundational no_std APIs for the fack workspace"
license = "GPL-3.0"
repository = "https://github.com/wafkse/fack"
homepage = "https://github.com/wafkse/fack"
documentation = "https://docs.rs/fack-core"
keywords = ["error", "no-std", "core"]
categories = ["no-std", "rust-patterns"]
readme = "../README.md"

[lints]
workspace = true
